/// Patient master dimension. One row per patient, SCD2-versioned by effective_start_date / effective_end_date.
/// Filter to is_current = 1 for the current view of a patient.
table dim_patient
	lineageTag: b1020001-0001-0001-0001-000000000001
	sourceLineageTag: [dbo].[dim_patient]

	/// Count of current patients (is_current = 1). SCD2 dimension — only counts the latest version of each patient.
	measure 'Total Patients' = CALCULATE(COUNTROWS(dim_patient), dim_patient[is_current] = 1)
		formatString: 0
		lineageTag: b1020001-0001-0001-0001-000000000011

	/// Distinct count of patients with at least one chronic diagnosis (dim_diagnosis.is_chronic = 1).
	measure 'Chronic Patients' =
			CALCULATE(
				DISTINCTCOUNT(fact_diagnosis[patient_key]),
				dim_diagnosis[is_chronic] = 1
			)
		formatString: 0
		lineageTag: b1020001-0001-0001-0001-000000000012

	/// Measure: chronic rate.
	measure 'Chronic Rate' =
			DIVIDE([Chronic Patients], [Total Patients])
		lineageTag: b1020001-0001-0001-0001-000000000013

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Average age across the current patient roster.
	measure 'Avg Patient Age' = AVERAGE(dim_patient[age])
		lineageTag: b1020001-0001-0001-0001-000000000014

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure: female patients.
	measure 'Female Patients' = CALCULATE([Total Patients], dim_patient[gender] = "Female")
		formatString: 0
		lineageTag: b1020001-0001-0001-0001-000000000015

	/// Measure: male patients.
	measure 'Male Patients' = CALCULATE([Total Patients], dim_patient[gender] = "Male")
		formatString: 0
		lineageTag: b1020001-0001-0001-0001-000000000016

	/// Patient business key. Stable across SCD2 versions.
	column patient_id
		dataType: string
		lineageTag: b1020001-0001-0001-0001-000000000021
		sourceLineageTag: patient_id
		summarizeBy: none
		sourceColumn: patient_id

		annotation SummarizationSetBy = Automatic

	/// Patient first name.
	column first_name
		dataType: string
		lineageTag: b1020001-0001-0001-0001-000000000022
		sourceLineageTag: first_name
		summarizeBy: none
		sourceColumn: first_name

		annotation SummarizationSetBy = Automatic

	/// Patient last name.
	column last_name
		dataType: string
		lineageTag: b1020001-0001-0001-0001-000000000023
		sourceLineageTag: last_name
		summarizeBy: none
		sourceColumn: last_name

		annotation SummarizationSetBy = Automatic

	/// Patient date of birth.
	column date_of_birth
		dataType: dateTime
		formatString: General Date
		lineageTag: b1020001-0001-0001-0001-000000000024
		sourceLineageTag: date_of_birth
		summarizeBy: none
		sourceColumn: date_of_birth

		annotation SummarizationSetBy = Automatic

	/// Patient gender (M / F / Other).
	column gender
		dataType: string
		lineageTag: b1020001-0001-0001-0001-000000000025
		sourceLineageTag: gender
		summarizeBy: none
		sourceColumn: gender

		annotation SummarizationSetBy = Automatic

	/// Street address. PII — hide from non-clinical users.
	column address
		dataType: string
		lineageTag: b1020001-0001-0001-0001-000000000026
		sourceLineageTag: address
		summarizeBy: none
		sourceColumn: address

		annotation SummarizationSetBy = Automatic

	/// Patient city.
	column city
		dataType: string
		lineageTag: b1020001-0001-0001-0001-000000000027
		sourceLineageTag: city
		dataCategory: City
		summarizeBy: none
		sourceColumn: city

		changedProperty = DataCategory

		annotation SummarizationSetBy = Automatic

	/// Patient state (US 2-letter code).
	column state
		dataType: string
		lineageTag: b1020001-0001-0001-0001-000000000028
		sourceLineageTag: state
		dataCategory: StateOrProvince
		summarizeBy: none
		sourceColumn: state

		changedProperty = DataCategory

		annotation SummarizationSetBy = Automatic

	/// Patient 5-digit ZIP. Join to dim_sdoh for community-level SDOH.
	column zip_code
		dataType: string
		lineageTag: b1020001-0001-0001-0001-000000000029
		sourceLineageTag: zip_code
		dataCategory: PostalCode
		summarizeBy: none
		sourceColumn: zip_code

		changedProperty = DataCategory

		annotation SummarizationSetBy = Automatic

	/// Patient phone. PII.
	column phone
		dataType: string
		lineageTag: b1020001-0001-0001-0001-00000000002a
		sourceLineageTag: phone
		summarizeBy: none
		sourceColumn: phone

		annotation SummarizationSetBy = Automatic

	/// Patient email. PII.
	column email
		dataType: string
		lineageTag: b1020001-0001-0001-0001-00000000002b
		sourceLineageTag: email
		summarizeBy: none
		sourceColumn: email

		annotation SummarizationSetBy = Automatic

	/// Self-reported insurance type (Commercial, Medicare, Medicaid, Self-Pay, Uninsured).
	column insurance_type
		dataType: string
		lineageTag: b1020001-0001-0001-0001-00000000002c
		sourceLineageTag: insurance_type
		summarizeBy: none
		sourceColumn: insurance_type

		annotation SummarizationSetBy = Automatic

	/// Self-reported insurance plan name.
	column insurance_provider
		dataType: string
		lineageTag: b1020001-0001-0001-0001-00000000002d
		sourceLineageTag: insurance_provider
		summarizeBy: none
		sourceColumn: insurance_provider

		annotation SummarizationSetBy = Automatic

	/// Patient insurance policy / member ID. PII.
	column insurance_policy_number
		dataType: string
		lineageTag: b1020001-0001-0001-0001-00000000002e
		sourceLineageTag: insurance_policy_number
		summarizeBy: none
		sourceColumn: insurance_policy_number

		annotation SummarizationSetBy = Automatic

	/// Patient age in years as of report date.
	column age
		dataType: int64
		formatString: 0
		lineageTag: b1020001-0001-0001-0001-00000000002f
		sourceLineageTag: age
		summarizeBy: none
		sourceColumn: age

		annotation SummarizationSetBy = Automatic

	/// Banded age cohort (e.g. 0-17, 18-44, 45-64, 65+).
	column age_group
		dataType: string
		lineageTag: b1020001-0001-0001-0001-000000000030
		sourceLineageTag: age_group
		summarizeBy: none
		sourceColumn: age_group

		annotation SummarizationSetBy = Automatic

	/// Surrogate key for joining to dim_patient. Changes across SCD2 versions.
	column patient_key
		dataType: int64
		formatString: 0
		lineageTag: b1020001-0001-0001-0001-000000000031
		sourceLineageTag: patient_key
		summarizeBy: none
		sourceColumn: patient_key

		annotation SummarizationSetBy = Automatic

	/// SCD2 flag — 1 = latest version of this entity; 0 = historical.
	column is_current
		dataType: int64
		formatString: 0
		lineageTag: b1020001-0001-0001-0001-000000000032
		sourceLineageTag: is_current
		summarizeBy: none
		sourceColumn: is_current

		annotation SummarizationSetBy = Automatic

	/// SCD2 — date this version of the patient record became current.
	column effective_start_date
		dataType: dateTime
		formatString: General Date
		lineageTag: b1020001-0001-0001-0001-000000000033
		sourceLineageTag: effective_start_date
		summarizeBy: none
		sourceColumn: effective_start_date

		annotation SummarizationSetBy = Automatic

	/// SCD2 — date this version was superseded.
	column effective_end_date
		dataType: dateTime
		formatString: General Date
		lineageTag: b1020001-0001-0001-0001-000000000034
		sourceLineageTag: effective_end_date
		summarizeBy: none
		sourceColumn: effective_end_date

		annotation SummarizationSetBy = Automatic

	/// ETL load audit timestamp. Internal — hide from end users.
	column _load_timestamp
		dataType: dateTime
		formatString: General Date
		lineageTag: b1020001-0001-0001-0001-000000000035
		sourceLineageTag: _load_timestamp
		summarizeBy: none
		sourceColumn: _load_timestamp

		annotation SummarizationSetBy = Automatic

	partition dim_patient = entity
		mode: directLake
		source
			entityName: dim_patient
			expressionSource: 'DirectLake - lh_gold_curated'
