table dim_provider
	lineageTag: b1010001-0001-0001-0001-000000000001
	sourceLineageTag: [dbo].[dim_provider]

	column provider_id
		dataType: string
		lineageTag: b1010001-0001-0001-0001-000000000011
		sourceLineageTag: provider_id
		summarizeBy: none
		sourceColumn: provider_id

		annotation SummarizationSetBy = Automatic

	column first_name
		dataType: string
		lineageTag: b1010001-0001-0001-0001-000000000012
		sourceLineageTag: first_name
		summarizeBy: none
		sourceColumn: first_name

		annotation SummarizationSetBy = Automatic

	column last_name
		dataType: string
		lineageTag: b1010001-0001-0001-0001-000000000013
		sourceLineageTag: last_name
		summarizeBy: none
		sourceColumn: last_name

		annotation SummarizationSetBy = Automatic

	column display_name
		dataType: string
		lineageTag: b1010001-0001-0001-0001-000000000014
		sourceLineageTag: display_name
		summarizeBy: none
		sourceColumn: display_name

		annotation SummarizationSetBy = Automatic

	column npi_number
		dataType: string
		lineageTag: b1010001-0001-0001-0001-000000000015
		sourceLineageTag: npi_number
		summarizeBy: none
		sourceColumn: npi_number

		annotation SummarizationSetBy = Automatic

	column specialty
		dataType: string
		lineageTag: b1010001-0001-0001-0001-000000000016
		sourceLineageTag: specialty
		summarizeBy: none
		sourceColumn: specialty

		annotation SummarizationSetBy = Automatic

	column department
		dataType: string
		lineageTag: b1010001-0001-0001-0001-000000000017
		sourceLineageTag: department
		summarizeBy: none
		sourceColumn: department

		annotation SummarizationSetBy = Automatic

	column facility_id
		dataType: string
		lineageTag: b1010001-0001-0001-0001-000000000018
		sourceLineageTag: facility_id
		summarizeBy: none
		sourceColumn: facility_id

		annotation SummarizationSetBy = Automatic

	column is_active
		dataType: int64
		formatString: 0
		lineageTag: b1010001-0001-0001-0001-000000000019
		sourceLineageTag: is_active
		summarizeBy: sum
		sourceColumn: is_active

		annotation SummarizationSetBy = Automatic

	column provider_key
		dataType: int64
		formatString: 0
		lineageTag: b1010001-0001-0001-0001-00000000001a
		sourceLineageTag: provider_key
		summarizeBy: none
		sourceColumn: provider_key

		annotation SummarizationSetBy = Automatic

	column is_current
		dataType: int64
		formatString: 0
		lineageTag: b1010001-0001-0001-0001-00000000001b
		sourceLineageTag: is_current
		summarizeBy: sum
		sourceColumn: is_current

		annotation SummarizationSetBy = Automatic

	column effective_start_date
		dataType: dateTime
		formatString: General Date
		lineageTag: b1010001-0001-0001-0001-00000000001c
		sourceLineageTag: effective_start_date
		summarizeBy: none
		sourceColumn: effective_start_date

		annotation SummarizationSetBy = Automatic

	column effective_end_date
		dataType: dateTime
		formatString: General Date
		lineageTag: b1010001-0001-0001-0001-00000000001d
		sourceLineageTag: effective_end_date
		summarizeBy: none
		sourceColumn: effective_end_date

		annotation SummarizationSetBy = Automatic

	column _load_timestamp
		dataType: dateTime
		formatString: General Date
		lineageTag: b1010001-0001-0001-0001-00000000001e
		sourceLineageTag: _load_timestamp
		summarizeBy: none
		sourceColumn: _load_timestamp

		annotation SummarizationSetBy = Automatic

	column contract_type
		dataType: string
		lineageTag: b1010001-0001-0001-0001-000000000021
		sourceLineageTag: contract_type
		summarizeBy: none
		sourceColumn: contract_type

		annotation SummarizationSetBy = Automatic

	column fte_status
		dataType: string
		lineageTag: b1010001-0001-0001-0001-000000000022
		sourceLineageTag: fte_status
		summarizeBy: none
		sourceColumn: fte_status

		annotation SummarizationSetBy = Automatic

	column years_experience
		dataType: int64
		formatString: 0
		lineageTag: b1010001-0001-0001-0001-000000000023
		sourceLineageTag: years_experience
		summarizeBy: none
		sourceColumn: years_experience

		annotation SummarizationSetBy = Automatic

	column board_certified
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: b1010001-0001-0001-0001-000000000024
		sourceLineageTag: board_certified
		summarizeBy: none
		sourceColumn: board_certified

		annotation SummarizationSetBy = Automatic

	column patient_panel_size
		dataType: int64
		formatString: #,##0
		lineageTag: b1010001-0001-0001-0001-000000000025
		sourceLineageTag: patient_panel_size
		summarizeBy: none
		sourceColumn: patient_panel_size

		annotation SummarizationSetBy = Automatic

	column annual_rvu_target
		dataType: int64
		formatString: #,##0
		lineageTag: b1010001-0001-0001-0001-000000000026
		sourceLineageTag: annual_rvu_target
		summarizeBy: none
		sourceColumn: annual_rvu_target

		annotation SummarizationSetBy = Automatic

	column actual_rvu
		dataType: int64
		formatString: #,##0
		lineageTag: b1010001-0001-0001-0001-000000000027
		sourceLineageTag: actual_rvu
		summarizeBy: none
		sourceColumn: actual_rvu

		annotation SummarizationSetBy = Automatic

	column patient_satisfaction_score
		dataType: double
		formatString: 0.0
		lineageTag: b1010001-0001-0001-0001-000000000028
		sourceLineageTag: patient_satisfaction_score
		summarizeBy: none
		sourceColumn: patient_satisfaction_score

		annotation SummarizationSetBy = Automatic

	column telehealth_enabled
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: b1010001-0001-0001-0001-000000000029
		sourceLineageTag: telehealth_enabled
		summarizeBy: none
		sourceColumn: telehealth_enabled

		annotation SummarizationSetBy = Automatic

	column documentation_score
		dataType: int64
		formatString: 0
		lineageTag: b1010001-0001-0001-0001-00000000002a
		sourceLineageTag: documentation_score
		summarizeBy: none
		sourceColumn: documentation_score

		annotation SummarizationSetBy = Automatic

	column ehr_adoption_score
		dataType: int64
		formatString: 0
		lineageTag: b1010001-0001-0001-0001-00000000002b
		sourceLineageTag: ehr_adoption_score
		summarizeBy: none
		sourceColumn: ehr_adoption_score

		annotation SummarizationSetBy = Automatic

	measure 'Avg Satisfaction Score' = AVERAGE(dim_provider[patient_satisfaction_score])
		formatString: 0.0
		lineageTag: b1010001-0001-0001-0001-000000000031

	measure 'Avg Documentation Score' = AVERAGE(dim_provider[documentation_score])
		formatString: 0
		lineageTag: b1010001-0001-0001-0001-000000000032

	measure 'Avg EHR Adoption Score' = AVERAGE(dim_provider[ehr_adoption_score])
		formatString: 0
		lineageTag: b1010001-0001-0001-0001-000000000033

	measure 'Telehealth Enabled Rate' = DIVIDE(CALCULATE(COUNTROWS(dim_provider), dim_provider[telehealth_enabled] = TRUE()), COUNTROWS(dim_provider))
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: b1010001-0001-0001-0001-000000000034

	measure 'Board Certified Rate' = DIVIDE(CALCULATE(COUNTROWS(dim_provider), dim_provider[board_certified] = TRUE()), COUNTROWS(dim_provider))
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: b1010001-0001-0001-0001-000000000035

	measure 'Avg Panel Size' = AVERAGE(dim_provider[patient_panel_size])
		formatString: #,##0
		lineageTag: b1010001-0001-0001-0001-000000000036

	measure 'Avg RVU Target' = AVERAGE(dim_provider[annual_rvu_target])
		formatString: #,##0
		lineageTag: b1010001-0001-0001-0001-000000000037

	measure 'Value-Based Provider Rate' = DIVIDE(CALCULATE(COUNTROWS(dim_provider), dim_provider[contract_type] = "Value-Based"), COUNTROWS(dim_provider))
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: b1010001-0001-0001-0001-000000000038

	measure 'Avg Actual RVU' = AVERAGE(dim_provider[actual_rvu])
		formatString: #,##0
		lineageTag: b1010001-0001-0001-0001-000000000039

	measure 'RVU Attainment %' = DIVIDE(SUM(dim_provider[actual_rvu]), SUM(dim_provider[annual_rvu_target]))
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: b1010001-0001-0001-0001-00000000003a

	measure 'Actual Panel Count' =
			VAR _current_provider = SELECTEDVALUE(dim_provider[provider_key])
			RETURN IF(ISBLANK(_current_provider), DIVIDE(DISTINCTCOUNT(fact_encounter[patient_key]), DISTINCTCOUNT(dim_provider[provider_key])), CALCULATE(DISTINCTCOUNT(fact_encounter[patient_key])))
		formatString: #,##0
		lineageTag: b1010001-0001-0001-0001-00000000003b

	measure 'Panel Utilization %' = DIVIDE([Actual Panel Count], [Avg Panel Size])
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: b1010001-0001-0001-0001-00000000003c

	measure 'Total Providers' = CALCULATE(COUNTROWS(dim_provider), dim_provider[is_current] = 1)
		formatString: 0
		lineageTag: b1010001-0001-0001-0001-00000000003d

	measure 'Full-Time Providers' = CALCULATE(COUNTROWS(dim_provider), dim_provider[fte_status] = "Full-time", dim_provider[is_current] = 1)
		formatString: 0
		lineageTag: b1010001-0001-0001-0001-00000000003e

	measure 'Avg Years Experience' = AVERAGE(dim_provider[years_experience])
		formatString: 0.0
		lineageTag: b1010001-0001-0001-0001-00000000003f

	partition dim_provider = entity
		mode: directLake
		source
			entityName: dim_provider
			expressionSource: 'DirectLake - lh_gold_curated'
