table fact_claim
	lineageTag: b1080001-0001-0001-0001-000000000001
	sourceLineageTag: [dbo].[fact_claim]

	measure 'Total Claims' = COUNTROWS(fact_claim)
		formatString: 0
		lineageTag: b1080001-0001-0001-0001-000000000011

	measure 'Denial Rate' =
			VAR _num = CALCULATE(COUNTROWS(fact_claim), fact_claim[denial_flag] = 1)
			VAR _den = COUNTROWS(fact_claim)
			RETURN DIVIDE(_num, _den)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: b1080001-0001-0001-0001-000000000012

	measure 'Total Billed' = SUM(fact_claim[billed_amount])
		lineageTag: b1080001-0001-0001-0001-000000000013

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Denial Risk' = AVERAGE(fact_claim[denial_risk_score])
		lineageTag: b1080001-0001-0001-0001-000000000014

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Provider Denial Count' = CALCULATE(COUNTROWS(fact_claim), fact_claim[denial_flag] = 1)
		formatString: 0
		lineageTag: b1080001-0001-0001-0001-000000000015

	column claim_id
		dataType: string
		lineageTag: b1080001-0001-0001-0001-000000000021
		sourceLineageTag: claim_id
		summarizeBy: none
		sourceColumn: claim_id

		annotation SummarizationSetBy = Automatic

	column claim_date_key
		dataType: int64
		formatString: 0
		lineageTag: b1080001-0001-0001-0001-000000000022
		sourceLineageTag: claim_date_key
		summarizeBy: none
		sourceColumn: claim_date_key

		annotation SummarizationSetBy = Automatic

	column patient_key
		dataType: int64
		formatString: 0
		lineageTag: b1080001-0001-0001-0001-000000000023
		sourceLineageTag: patient_key
		summarizeBy: none
		sourceColumn: patient_key

		annotation SummarizationSetBy = Automatic

	column provider_key
		dataType: int64
		formatString: 0
		lineageTag: b1080001-0001-0001-0001-000000000024
		sourceLineageTag: provider_key
		summarizeBy: none
		sourceColumn: provider_key

		annotation SummarizationSetBy = Automatic

	column encounter_key
		dataType: int64
		formatString: 0
		lineageTag: b1080001-0001-0001-0001-000000000025
		sourceLineageTag: encounter_key
		summarizeBy: sum
		sourceColumn: encounter_key

		annotation SummarizationSetBy = Automatic

	column claim_type
		dataType: string
		lineageTag: b1080001-0001-0001-0001-000000000026
		sourceLineageTag: claim_type
		summarizeBy: none
		sourceColumn: claim_type

		annotation SummarizationSetBy = Automatic

	column claim_status
		dataType: string
		lineageTag: b1080001-0001-0001-0001-000000000027
		sourceLineageTag: claim_status
		summarizeBy: none
		sourceColumn: claim_status

		annotation SummarizationSetBy = Automatic

	column billed_amount
		dataType: double
		lineageTag: b1080001-0001-0001-0001-000000000028
		sourceLineageTag: billed_amount
		summarizeBy: sum
		sourceColumn: billed_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column paid_amount
		dataType: double
		lineageTag: b1080001-0001-0001-0001-000000000029
		sourceLineageTag: paid_amount
		summarizeBy: sum
		sourceColumn: paid_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column denial_flag
		dataType: int64
		formatString: 0
		lineageTag: b1080001-0001-0001-0001-00000000002a
		sourceLineageTag: denial_flag
		summarizeBy: sum
		sourceColumn: denial_flag

		annotation SummarizationSetBy = Automatic

	column denial_risk_score
		dataType: double
		lineageTag: b1080001-0001-0001-0001-00000000002b
		sourceLineageTag: denial_risk_score
		summarizeBy: sum
		sourceColumn: denial_risk_score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column denial_risk_category
		dataType: string
		lineageTag: b1080001-0001-0001-0001-00000000002c
		sourceLineageTag: denial_risk_category
		summarizeBy: none
		sourceColumn: denial_risk_category

		annotation SummarizationSetBy = Automatic

	column primary_denial_reason
		dataType: string
		lineageTag: b1080001-0001-0001-0001-00000000002d
		sourceLineageTag: primary_denial_reason
		summarizeBy: none
		sourceColumn: primary_denial_reason

		annotation SummarizationSetBy = Automatic

	column _load_timestamp
		dataType: dateTime
		formatString: General Date
		lineageTag: b1080001-0001-0001-0001-00000000002e
		sourceLineageTag: _load_timestamp
		summarizeBy: none
		sourceColumn: _load_timestamp

		annotation SummarizationSetBy = Automatic

	column claim_key
		dataType: int64
		formatString: 0
		lineageTag: b1080001-0001-0001-0001-00000000002f
		sourceLineageTag: claim_key
		summarizeBy: sum
		sourceColumn: claim_key

		annotation SummarizationSetBy = Automatic

	partition fact_claim = entity
		mode: directLake
		source
			entityName: fact_claim
			expressionSource: 'DirectLake - lh_gold_curated'
