/// Patient diagnosis fact. One row per (patient, diagnosis, encounter). diagnosis_type = 'Primary' identifies the
/// principal diagnosis on an encounter.
table fact_diagnosis
	lineageTag: b10a0001-0001-0001-0001-000000000001
	sourceLineageTag: [dbo].[fact_diagnosis]

	/// Measure: unique diagnoses.
	measure 'Unique Diagnoses' = DISTINCTCOUNT(fact_diagnosis[diagnosis_key])
		formatString: 0
		lineageTag: b10a0001-0001-0001-0001-000000000011

	/// Measure: chronic diagnoses.
	measure 'Chronic Diagnoses' =
			CALCULATE(
				DISTINCTCOUNT(fact_diagnosis[diagnosis_key]),
				dim_diagnosis[is_chronic] = 1
			)
		formatString: 0
		lineageTag: b10a0001-0001-0001-0001-000000000012

	/// Measure: patients with chronic conditions.
	measure 'Patients with Chronic Conditions' =
			CALCULATE(
				DISTINCTCOUNT(fact_diagnosis[patient_key]),
				dim_diagnosis[is_chronic] = 1
			)
		formatString: 0
		lineageTag: b10a0001-0001-0001-0001-000000000013

	/// Surrogate join key.
	column fact_diagnosis_key
		dataType: int64
		formatString: 0
		lineageTag: b10a0001-0001-0001-0001-000000000021
		sourceLineageTag: fact_diagnosis_key
		summarizeBy: none
		sourceColumn: fact_diagnosis_key

		annotation SummarizationSetBy = Automatic

	/// Business key.
	column diagnosis_id
		dataType: string
		lineageTag: b10a0001-0001-0001-0001-000000000022
		sourceLineageTag: diagnosis_id
		summarizeBy: none
		sourceColumn: diagnosis_id

		annotation SummarizationSetBy = Automatic

	/// Surrogate join key.
	column encounter_key
		dataType: int64
		formatString: 0
		lineageTag: b10a0001-0001-0001-0001-000000000023
		sourceLineageTag: encounter_key
		summarizeBy: none
		sourceColumn: encounter_key

		annotation SummarizationSetBy = Automatic

	/// Surrogate join key.
	column diagnosis_date_key
		dataType: int64
		formatString: 0
		lineageTag: b10a0001-0001-0001-0001-000000000024
		sourceLineageTag: diagnosis_date_key
		summarizeBy: none
		sourceColumn: diagnosis_date_key

		annotation SummarizationSetBy = Automatic

	/// Surrogate key for joining to dim_patient. Changes across SCD2 versions.
	column patient_key
		dataType: int64
		formatString: 0
		lineageTag: b10a0001-0001-0001-0001-000000000025
		sourceLineageTag: patient_key
		summarizeBy: none
		sourceColumn: patient_key

		annotation SummarizationSetBy = Automatic

	/// Surrogate key for joining to dim_diagnosis.
	column diagnosis_key
		dataType: int64
		formatString: 0
		lineageTag: b10a0001-0001-0001-0001-000000000026
		sourceLineageTag: diagnosis_key
		summarizeBy: none
		sourceColumn: diagnosis_key

		annotation SummarizationSetBy = Automatic

	/// Surrogate join key.
	column facility_key
		dataType: int64
		formatString: 0
		lineageTag: b10a0001-0001-0001-0001-000000000027
		sourceLineageTag: facility_key
		summarizeBy: none
		sourceColumn: facility_key

		annotation SummarizationSetBy = Automatic

	/// Icd code.
	column icd_code
		dataType: string
		lineageTag: b10a0001-0001-0001-0001-000000000028
		sourceLineageTag: icd_code
		summarizeBy: none
		sourceColumn: icd_code

		annotation SummarizationSetBy = Automatic

	/// Diagnosis sequence.
	column diagnosis_sequence
		dataType: int64
		formatString: 0
		lineageTag: b10a0001-0001-0001-0001-000000000029
		sourceLineageTag: diagnosis_sequence
		summarizeBy: sum
		sourceColumn: diagnosis_sequence

		annotation SummarizationSetBy = Automatic

	/// Diagnosis type.
	column diagnosis_type
		dataType: string
		lineageTag: b10a0001-0001-0001-0001-00000000002a
		sourceLineageTag: diagnosis_type
		summarizeBy: none
		sourceColumn: diagnosis_type

		annotation SummarizationSetBy = Automatic

	/// Present on admission.
	column present_on_admission
		dataType: string
		lineageTag: b10a0001-0001-0001-0001-00000000002b
		sourceLineageTag: present_on_admission
		summarizeBy: none
		sourceColumn: present_on_admission

		annotation SummarizationSetBy = Automatic

	/// ETL load audit timestamp. Internal — hide from end users.
	column _load_timestamp
		dataType: dateTime
		formatString: General Date
		lineageTag: b10a0001-0001-0001-0001-00000000002c
		sourceLineageTag: _load_timestamp
		summarizeBy: none
		sourceColumn: _load_timestamp

		annotation SummarizationSetBy = Automatic

	partition fact_diagnosis = entity
		mode: directLake
		source
			entityName: fact_diagnosis
			expressionSource: 'DirectLake - lh_gold_curated'
