table fact_prescription
	lineageTag: b1090001-0001-0001-0001-000000000001
	sourceLineageTag: [dbo].[fact_prescription]

	measure 'Total Fills' = COUNTROWS(fact_prescription)
		formatString: 0
		lineageTag: b1090001-0001-0001-0001-000000000011

	measure 'Total Rx Cost' = SUM(fact_prescription[total_cost])
		lineageTag: b1090001-0001-0001-0001-000000000012

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Rx Cost Per Fill' = DIVIDE([Total Rx Cost], [Total Fills])
		lineageTag: b1090001-0001-0001-0001-000000000013

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Generic Fill Rate' =
			VAR _generic = CALCULATE(COUNTROWS(fact_prescription), fact_prescription[is_generic] = 1)
			VAR _total = COUNTROWS(fact_prescription)
			RETURN DIVIDE(_generic, _total)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: b1090001-0001-0001-0001-000000000014

	measure 'Unique Medications Prescribed' = DISTINCTCOUNT(fact_prescription[medication_key])
		formatString: 0
		lineageTag: b1090001-0001-0001-0001-000000000015

	column prescription_id
		dataType: string
		lineageTag: b1090001-0001-0001-0001-000000000021
		sourceLineageTag: prescription_id
		summarizeBy: none
		sourceColumn: prescription_id

		annotation SummarizationSetBy = Automatic

	column prescription_group_id
		dataType: string
		lineageTag: b1090001-0001-0001-0001-000000000022
		sourceLineageTag: prescription_group_id
		summarizeBy: none
		sourceColumn: prescription_group_id

		annotation SummarizationSetBy = Automatic

	column fill_date_key
		dataType: int64
		formatString: 0
		lineageTag: b1090001-0001-0001-0001-000000000023
		sourceLineageTag: fill_date_key
		summarizeBy: none
		sourceColumn: fill_date_key

		annotation SummarizationSetBy = Automatic

	column patient_key
		dataType: int64
		formatString: 0
		lineageTag: b1090001-0001-0001-0001-000000000024
		sourceLineageTag: patient_key
		summarizeBy: none
		sourceColumn: patient_key

		annotation SummarizationSetBy = Automatic

	column provider_key
		dataType: int64
		formatString: 0
		lineageTag: b1090001-0001-0001-0001-000000000025
		sourceLineageTag: provider_key
		summarizeBy: none
		sourceColumn: provider_key

		annotation SummarizationSetBy = Automatic

	column encounter_key
		dataType: int64
		formatString: 0
		lineageTag: b1090001-0001-0001-0001-000000000026
		sourceLineageTag: encounter_key
		summarizeBy: sum
		sourceColumn: encounter_key

		annotation SummarizationSetBy = Automatic

	column medication_key
		dataType: int64
		formatString: 0
		lineageTag: b1090001-0001-0001-0001-000000000027
		sourceLineageTag: medication_key
		summarizeBy: none
		sourceColumn: medication_key

		annotation SummarizationSetBy = Automatic

	column fill_number
		dataType: int64
		formatString: 0
		lineageTag: b1090001-0001-0001-0001-000000000028
		sourceLineageTag: fill_number
		summarizeBy: sum
		sourceColumn: fill_number

		annotation SummarizationSetBy = Automatic

	column days_supply
		dataType: int64
		formatString: 0
		lineageTag: b1090001-0001-0001-0001-000000000029
		sourceLineageTag: days_supply
		summarizeBy: sum
		sourceColumn: days_supply

		annotation SummarizationSetBy = Automatic

	column quantity_dispensed
		dataType: int64
		formatString: 0
		lineageTag: b1090001-0001-0001-0001-00000000002a
		sourceLineageTag: quantity_dispensed
		summarizeBy: sum
		sourceColumn: quantity_dispensed

		annotation SummarizationSetBy = Automatic

	column is_generic
		dataType: int64
		formatString: 0
		lineageTag: b1090001-0001-0001-0001-00000000002b
		sourceLineageTag: is_generic
		summarizeBy: sum
		sourceColumn: is_generic

		annotation SummarizationSetBy = Automatic

	column is_chronic_medication
		dataType: int64
		formatString: 0
		lineageTag: b1090001-0001-0001-0001-00000000002c
		sourceLineageTag: is_chronic_medication
		summarizeBy: sum
		sourceColumn: is_chronic_medication

		annotation SummarizationSetBy = Automatic

	column total_cost
		dataType: double
		lineageTag: b1090001-0001-0001-0001-00000000002d
		sourceLineageTag: total_cost
		summarizeBy: sum
		sourceColumn: total_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column payer_paid
		dataType: double
		lineageTag: b1090001-0001-0001-0001-00000000002e
		sourceLineageTag: payer_paid
		summarizeBy: sum
		sourceColumn: payer_paid

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column patient_copay
		dataType: double
		lineageTag: b1090001-0001-0001-0001-00000000002f
		sourceLineageTag: patient_copay
		summarizeBy: sum
		sourceColumn: patient_copay

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column _load_timestamp
		dataType: dateTime
		formatString: General Date
		lineageTag: b1090001-0001-0001-0001-000000000030
		sourceLineageTag: _load_timestamp
		summarizeBy: none
		sourceColumn: _load_timestamp

		annotation SummarizationSetBy = Automatic

	column prescription_key
		dataType: int64
		formatString: 0
		lineageTag: b1090001-0001-0001-0001-000000000031
		sourceLineageTag: prescription_key
		summarizeBy: sum
		sourceColumn: prescription_key

		annotation SummarizationSetBy = Automatic

	partition fact_prescription = entity
		mode: directLake
		source
			entityName: fact_prescription
			expressionSource: 'DirectLake - lh_gold_curated'
