/// Risk Adjustment Factor (RAF) score per member-year, used for Medicare Advantage risk adjustment.
table agg_raf_score
	lineageTag: c1240001-0001-0001-0001-000000000001
	sourceLineageTag: [dbo].[agg_raf_score]

	/// Average Risk Adjustment Factor across members. Higher RAF indicates a sicker population and more risk-adjusted
	/// revenue.
	measure 'Avg RAF Score' = AVERAGE(agg_raf_score[raf_score])
		formatString: 0.00
		lineageTag: c1240001-0001-0001-0001-000000000011
		displayFolder: Risk

	/// Average count of Hierarchical Condition Categories per member.
	measure 'Avg HCC Count' = AVERAGE(agg_raf_score[hcc_count])
		formatString: 0.0
		lineageTag: c1240001-0001-0001-0001-000000000012
		displayFolder: Utilization

	/// Distinct count of members with at least one HCC.
	measure 'Members with HCCs' = CALCULATE(DISTINCTCOUNT(agg_raf_score[member_key]), agg_raf_score[hcc_count] > 0)
		formatString: #,##0
		lineageTag: c1240001-0001-0001-0001-000000000013

	/// Business key.
	column raf_id
		dataType: string
		lineageTag: c1240001-0001-0001-0001-000000000021
		sourceLineageTag: raf_id
		summarizeBy: none
		sourceColumn: raf_id
		annotation SummarizationSetBy = Automatic

	/// Surrogate join key.
	column member_key
		isHidden: true
		dataType: int64
		formatString: 0
		lineageTag: c1240001-0001-0001-0001-000000000022
		sourceLineageTag: member_key
		summarizeBy: none
		sourceColumn: member_key
		annotation SummarizationSetBy = Automatic

	/// Surrogate key for joining to dim_payer.
	column payer_key
		isHidden: true
		dataType: int64
		formatString: 0
		lineageTag: c1240001-0001-0001-0001-000000000023
		sourceLineageTag: payer_key
		summarizeBy: none
		sourceColumn: payer_key
		annotation SummarizationSetBy = Automatic

	/// Surrogate key for joining to dim_plan.
	column plan_key
		isHidden: true
		dataType: int64
		formatString: 0
		lineageTag: c1240001-0001-0001-0001-000000000024
		sourceLineageTag: plan_key
		summarizeBy: none
		sourceColumn: plan_key
		annotation SummarizationSetBy = Automatic

	/// Measurement year.
	column measurement_year
		dataType: int64
		formatString: 0
		lineageTag: c1240001-0001-0001-0001-000000000025
		sourceLineageTag: measurement_year
		summarizeBy: none
		sourceColumn: measurement_year
		annotation SummarizationSetBy = Automatic

	/// Count of records in the underlying grain.
	column hcc_count
		dataType: int64
		formatString: 0
		lineageTag: c1240001-0001-0001-0001-000000000026
		sourceLineageTag: hcc_count
		summarizeBy: sum
		sourceColumn: hcc_count
		annotation SummarizationSetBy = Automatic

	/// Hcc codes.
	column hcc_codes
		dataType: string
		lineageTag: c1240001-0001-0001-0001-000000000027
		sourceLineageTag: hcc_codes
		summarizeBy: none
		sourceColumn: hcc_codes
		annotation SummarizationSetBy = Automatic

	/// Model-produced score.
	column demographic_score
		dataType: double
		lineageTag: c1240001-0001-0001-0001-000000000028
		sourceLineageTag: demographic_score
		summarizeBy: average
		sourceColumn: demographic_score
		annotation SummarizationSetBy = Automatic

	/// Model-produced score.
	column disease_score
		dataType: double
		lineageTag: c1240001-0001-0001-0001-000000000029
		sourceLineageTag: disease_score
		summarizeBy: average
		sourceColumn: disease_score
		annotation SummarizationSetBy = Automatic

	/// Model-produced score.
	column raf_score
		dataType: double
		lineageTag: c1240001-0001-0001-0001-00000000002a
		sourceLineageTag: raf_score
		summarizeBy: average
		sourceColumn: raf_score
		annotation SummarizationSetBy = Automatic

	partition agg_raf_score = entity
		mode: directLake
		source
			entityName: agg_raf_score
			expressionSource: 'DirectLake - lh_gold_curated'
