table agg_star_rating_overall
	lineageTag: c1230001-0001-0001-0001-000000000001
	sourceLineageTag: [dbo].[agg_star_rating_overall]

	measure 'Overall Star Score' = AVERAGE(agg_star_rating_overall[overall_star_score])
		formatString: 0.00
		lineageTag: c1230001-0001-0001-0001-000000000011

	column payer_key
		dataType: int64
		formatString: 0
		lineageTag: c1230001-0001-0001-0001-000000000021
		sourceLineageTag: payer_key
		summarizeBy: none
		sourceColumn: payer_key
		annotation SummarizationSetBy = Automatic

	column measurement_year
		dataType: int64
		formatString: 0
		lineageTag: c1230001-0001-0001-0001-000000000022
		sourceLineageTag: measurement_year
		summarizeBy: none
		sourceColumn: measurement_year
		annotation SummarizationSetBy = Automatic

	column overall_star_score
		dataType: double
		lineageTag: c1230001-0001-0001-0001-000000000023
		sourceLineageTag: overall_star_score
		summarizeBy: average
		sourceColumn: overall_star_score
		annotation SummarizationSetBy = Automatic

	column total_weight
		dataType: int64
		formatString: 0
		lineageTag: c1230001-0001-0001-0001-000000000024
		sourceLineageTag: total_weight
		summarizeBy: sum
		sourceColumn: total_weight
		annotation SummarizationSetBy = Automatic

	column measure_count
		dataType: int64
		formatString: 0
		lineageTag: c1230001-0001-0001-0001-000000000025
		sourceLineageTag: measure_count
		summarizeBy: sum
		sourceColumn: measure_count
		annotation SummarizationSetBy = Automatic

	partition agg_star_rating_overall = entity
		mode: directLake
		source
			entityName: agg_star_rating_overall
			expressionSource: 'DirectLake - lh_gold_curated'
