table dim_patient
	lineageTag: c1030001-0001-0001-0001-000000000001
	sourceLineageTag: [dbo].[dim_patient]

	measure 'Total Patients' = CALCULATE(COUNTROWS(dim_patient), dim_patient[is_current] = 1)
		formatString: 0
		lineageTag: c1030001-0001-0001-0001-000000000011

	measure 'Chronic Patients' =
			CALCULATE(
				DISTINCTCOUNT(fact_diagnosis[patient_key]),
				dim_diagnosis[is_chronic] = 1
			)
		formatString: 0
		lineageTag: c1030001-0001-0001-0001-000000000012

	measure 'Avg Patient Age' = AVERAGE(dim_patient[age])
		lineageTag: c1030001-0001-0001-0001-000000000013

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column patient_id
		dataType: string
		lineageTag: c1030001-0001-0001-0001-000000000021
		sourceLineageTag: patient_id
		summarizeBy: none
		sourceColumn: patient_id

		annotation SummarizationSetBy = Automatic

	column first_name
		dataType: string
		lineageTag: c1030001-0001-0001-0001-000000000022
		sourceLineageTag: first_name
		summarizeBy: none
		sourceColumn: first_name

		annotation SummarizationSetBy = Automatic

	column last_name
		dataType: string
		lineageTag: c1030001-0001-0001-0001-000000000023
		sourceLineageTag: last_name
		summarizeBy: none
		sourceColumn: last_name

		annotation SummarizationSetBy = Automatic

	column date_of_birth
		dataType: dateTime
		formatString: General Date
		lineageTag: c1030001-0001-0001-0001-000000000024
		sourceLineageTag: date_of_birth
		summarizeBy: none
		sourceColumn: date_of_birth

		annotation SummarizationSetBy = Automatic

	column gender
		dataType: string
		lineageTag: c1030001-0001-0001-0001-000000000025
		sourceLineageTag: gender
		summarizeBy: none
		sourceColumn: gender

		annotation SummarizationSetBy = Automatic

	column address
		dataType: string
		lineageTag: c1030001-0001-0001-0001-000000000026
		sourceLineageTag: address
		summarizeBy: none
		sourceColumn: address

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: c1030001-0001-0001-0001-000000000027
		sourceLineageTag: city
		dataCategory: City
		summarizeBy: none
		sourceColumn: city

		changedProperty = DataCategory

		annotation SummarizationSetBy = Automatic

	column state
		dataType: string
		lineageTag: c1030001-0001-0001-0001-000000000028
		sourceLineageTag: state
		dataCategory: StateOrProvince
		summarizeBy: none
		sourceColumn: state

		changedProperty = DataCategory

		annotation SummarizationSetBy = Automatic

	column zip_code
		dataType: string
		lineageTag: c1030001-0001-0001-0001-000000000029
		sourceLineageTag: zip_code
		dataCategory: PostalCode
		summarizeBy: none
		sourceColumn: zip_code

		changedProperty = DataCategory

		annotation SummarizationSetBy = Automatic

	column phone
		dataType: string
		lineageTag: c1030001-0001-0001-0001-00000000002a
		sourceLineageTag: phone
		summarizeBy: none
		sourceColumn: phone

		annotation SummarizationSetBy = Automatic

	column email
		dataType: string
		lineageTag: c1030001-0001-0001-0001-00000000002b
		sourceLineageTag: email
		summarizeBy: none
		sourceColumn: email

		annotation SummarizationSetBy = Automatic

	column insurance_type
		dataType: string
		lineageTag: c1030001-0001-0001-0001-00000000002c
		sourceLineageTag: insurance_type
		summarizeBy: none
		sourceColumn: insurance_type

		annotation SummarizationSetBy = Automatic

	column insurance_provider
		dataType: string
		lineageTag: c1030001-0001-0001-0001-00000000002d
		sourceLineageTag: insurance_provider
		summarizeBy: none
		sourceColumn: insurance_provider

		annotation SummarizationSetBy = Automatic

	column insurance_policy_number
		dataType: string
		lineageTag: c1030001-0001-0001-0001-00000000002e
		sourceLineageTag: insurance_policy_number
		summarizeBy: none
		sourceColumn: insurance_policy_number

		annotation SummarizationSetBy = Automatic

	column age
		dataType: int64
		formatString: 0
		lineageTag: c1030001-0001-0001-0001-00000000002f
		sourceLineageTag: age
		summarizeBy: sum
		sourceColumn: age

		annotation SummarizationSetBy = Automatic

	column age_group
		dataType: string
		lineageTag: c1030001-0001-0001-0001-000000000030
		sourceLineageTag: age_group
		summarizeBy: none
		sourceColumn: age_group

		annotation SummarizationSetBy = Automatic

	column patient_key
		dataType: int64
		formatString: 0
		lineageTag: c1030001-0001-0001-0001-000000000031
		sourceLineageTag: patient_key
		summarizeBy: none
		sourceColumn: patient_key

		annotation SummarizationSetBy = Automatic

	column is_current
		dataType: int64
		formatString: 0
		lineageTag: c1030001-0001-0001-0001-000000000032
		sourceLineageTag: is_current
		summarizeBy: sum
		sourceColumn: is_current

		annotation SummarizationSetBy = Automatic

	column effective_start_date
		dataType: dateTime
		formatString: General Date
		lineageTag: c1030001-0001-0001-0001-000000000033
		sourceLineageTag: effective_start_date
		summarizeBy: none
		sourceColumn: effective_start_date

		annotation SummarizationSetBy = Automatic

	column effective_end_date
		dataType: dateTime
		formatString: General Date
		lineageTag: c1030001-0001-0001-0001-000000000034
		sourceLineageTag: effective_end_date
		summarizeBy: none
		sourceColumn: effective_end_date

		annotation SummarizationSetBy = Automatic

	column _load_timestamp
		dataType: dateTime
		formatString: General Date
		lineageTag: c1030001-0001-0001-0001-000000000035
		sourceLineageTag: _load_timestamp
		summarizeBy: none
		sourceColumn: _load_timestamp

		annotation SummarizationSetBy = Automatic

	partition dim_patient = entity
		mode: directLake
		source
			entityName: dim_patient
			expressionSource: 'DirectLake - lh_gold_curated'
