/// Encounter fact. One row per inpatient or outpatient visit. readmission_risk_category and encounter_type are
/// the canonical filters.
table fact_encounter
	lineageTag: c1080001-0001-0001-0001-000000000001
	sourceLineageTag: [dbo].[fact_encounter]

	/// Measure: total encounters.
	measure 'Total Encounters' = COUNTROWS(fact_encounter)
		formatString: 0
		lineageTag: c1080001-0001-0001-0001-000000000011
		displayFolder: Volume

	/// Measure: total charges.
	measure 'Total Charges' = SUM(fact_encounter[total_charges])
		formatString: "\$#,0;(\$#,0);\$0"
		lineageTag: c1080001-0001-0001-0001-000000000012
		displayFolder: Financials

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure: total cost.
	measure 'Total Cost' = SUM(fact_encounter[total_cost])
		formatString: "\$#,0;(\$#,0);\$0"
		lineageTag: c1080001-0001-0001-0001-000000000013
		displayFolder: Financials

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure: total expected reimbursement.
	measure 'Total Expected Reimbursement' = SUM(fact_encounter[expected_reimbursement])
		lineageTag: c1080001-0001-0001-0001-000000000014
		displayFolder: Volume

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure: avg drg weight.
	measure 'Avg DRG Weight' = AVERAGE(fact_encounter[drg_weight])
		lineageTag: c1080001-0001-0001-0001-000000000015
		displayFolder: Utilization

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure: pmpm.
	measure PMPM =
			VAR _total = [Total Charges]
			VAR _members = DISTINCTCOUNT(fact_encounter[patient_key])
			VAR _months = DISTINCTCOUNT(dim_date[month_number])
			RETURN DIVIDE(_total, _members * _months)
		lineageTag: c1080001-0001-0001-0001-000000000016

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure: avg cost per encounter.
	measure 'Avg Cost Per Encounter' = DIVIDE([Total Cost], [Total Encounters])
		formatString: "\$#,0;(\$#,0);\$0"
		lineageTag: c1080001-0001-0001-0001-000000000017
		displayFolder: Financials

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure: inpatient encounters.
	measure 'Inpatient Encounters' = CALCULATE(COUNTROWS(fact_encounter), fact_encounter[encounter_type] = "Inpatient")
		formatString: 0
		lineageTag: c1080001-0001-0001-0001-000000000018
		displayFolder: Utilization

	/// Measure: emergency encounters.
	measure 'Emergency Encounters' = CALCULATE(COUNTROWS(fact_encounter), fact_encounter[encounter_type] = "Emergency")
		formatString: 0
		lineageTag: c1080001-0001-0001-0001-000000000019

	/// Measure: readmission rate.
	measure 'Readmission Rate' =
			VAR _num = CALCULATE(COUNTROWS(fact_encounter), fact_encounter[readmission_flag] = 1)
			VAR _den = COUNTROWS(fact_encounter)
			RETURN DIVIDE(_num, _den)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: c1080001-0001-0001-0001-00000000001a
		displayFolder: Risk

	/// Measure: avg length of stay.
	measure 'Avg Length of Stay' = AVERAGE(fact_encounter[length_of_stay])
		lineageTag: c1080001-0001-0001-0001-00000000001b
		displayFolder: Utilization

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure: py charges.
	measure 'PY Charges' = CALCULATE(SUM(fact_encounter[total_charges]), SAMEPERIODLASTYEAR(dim_date[full_date]))
		lineageTag: c1080001-0001-0001-0001-00000000001c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure: yoy charge growth.
	measure 'YoY Charge Growth' =
			VAR _cy = [Total Charges]
			VAR _py = [PY Charges]
			RETURN DIVIDE(_cy - _py, _py)
		lineageTag: c1080001-0001-0001-0001-00000000001d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure: ytd charges.
	measure 'YTD Charges' = CALCULATE([Total Charges], DATESYTD(dim_date[full_date]))
		lineageTag: c1080001-0001-0001-0001-00000000001e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Encounter business key.
	column encounter_id
		dataType: string
		lineageTag: c1080001-0001-0001-0001-000000000031
		sourceLineageTag: encounter_id
		summarizeBy: none
		sourceColumn: encounter_id

		annotation SummarizationSetBy = Automatic

	/// Date the encounter occurred, as YYYYMMDD integer. Join to dim_date.
	column encounter_date_key
		isHidden: true
		dataType: int64
		formatString: 0
		lineageTag: c1080001-0001-0001-0001-000000000032
		sourceLineageTag: encounter_date_key
		summarizeBy: none
		sourceColumn: encounter_date_key

		annotation SummarizationSetBy = Automatic

	/// Surrogate join key.
	column discharge_date_key
		isHidden: true
		dataType: int64
		formatString: 0
		lineageTag: c1080001-0001-0001-0001-000000000033
		sourceLineageTag: discharge_date_key
		summarizeBy: none
		sourceColumn: discharge_date_key

		annotation SummarizationSetBy = Automatic

	/// Surrogate key for joining to dim_patient. Changes across SCD2 versions.
	column patient_key
		isHidden: true
		dataType: int64
		formatString: 0
		lineageTag: c1080001-0001-0001-0001-000000000034
		sourceLineageTag: patient_key
		summarizeBy: none
		sourceColumn: patient_key

		annotation SummarizationSetBy = Automatic

	/// Surrogate key for joining to dim_provider.
	column provider_key
		isHidden: true
		dataType: int64
		formatString: 0
		lineageTag: c1080001-0001-0001-0001-000000000035
		sourceLineageTag: provider_key
		summarizeBy: none
		sourceColumn: provider_key

		annotation SummarizationSetBy = Automatic

	/// Surrogate join key.
	column facility_key
		isHidden: true
		dataType: int64
		formatString: 0
		lineageTag: c1080001-0001-0001-0001-000000000036
		sourceLineageTag: facility_key
		summarizeBy: none
		sourceColumn: facility_key

		annotation SummarizationSetBy = Automatic

	/// Encounter type: Inpatient, Outpatient, Emergency, Observation.
	column encounter_type
		dataType: string
		lineageTag: c1080001-0001-0001-0001-000000000037
		sourceLineageTag: encounter_type
		summarizeBy: none
		sourceColumn: encounter_type

		annotation SummarizationSetBy = Automatic

	/// Admission type.
	column admission_type
		dataType: string
		lineageTag: c1080001-0001-0001-0001-000000000038
		sourceLineageTag: admission_type
		summarizeBy: none
		sourceColumn: admission_type

		annotation SummarizationSetBy = Automatic

	/// Discharge disposition.
	column discharge_disposition
		dataType: string
		lineageTag: c1080001-0001-0001-0001-000000000039
		sourceLineageTag: discharge_disposition
		summarizeBy: none
		sourceColumn: discharge_disposition

		annotation SummarizationSetBy = Automatic

	/// Length of stay in days (inpatient only).
	column length_of_stay
		dataType: int64
		formatString: 0
		lineageTag: c1080001-0001-0001-0001-00000000003a
		sourceLineageTag: length_of_stay
		summarizeBy: sum
		sourceColumn: length_of_stay

		annotation SummarizationSetBy = Automatic

	/// Total billed charges for the encounter.
	column total_charges
		dataType: double
		lineageTag: c1080001-0001-0001-0001-00000000003b
		sourceLineageTag: total_charges
		summarizeBy: sum
		sourceColumn: total_charges

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Total cost to deliver the encounter (provider-side).
	column total_cost
		dataType: double
		lineageTag: c1080001-0001-0001-0001-00000000003c
		sourceLineageTag: total_cost
		summarizeBy: sum
		sourceColumn: total_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Boolean flag (1 = true, 0 = false).
	column readmission_flag
		dataType: int64
		formatString: 0
		lineageTag: c1080001-0001-0001-0001-00000000003d
		sourceLineageTag: readmission_flag
		summarizeBy: none
		sourceColumn: readmission_flag

		annotation SummarizationSetBy = Automatic

	/// Model probability of 30-day readmission (0-1). Do NOT filter directly; use readmission_risk_category.
	column readmission_risk_score
		dataType: double
		lineageTag: c1080001-0001-0001-0001-00000000003e
		sourceLineageTag: readmission_risk_score
		summarizeBy: none
		sourceColumn: readmission_risk_score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Readmission risk band: High, Medium, Low. Preferred filter for risk.
	column readmission_risk_category
		dataType: string
		lineageTag: c1080001-0001-0001-0001-00000000003f
		sourceLineageTag: readmission_risk_category
		summarizeBy: none
		sourceColumn: readmission_risk_category

		annotation SummarizationSetBy = Automatic

	/// Drg code.
	column drg_code
		dataType: string
		lineageTag: c1080001-0001-0001-0001-000000000040
		sourceLineageTag: drg_code
		summarizeBy: none
		sourceColumn: drg_code

		annotation SummarizationSetBy = Automatic

	/// Drg description.
	column drg_description
		dataType: string
		lineageTag: c1080001-0001-0001-0001-000000000041
		sourceLineageTag: drg_description
		summarizeBy: none
		sourceColumn: drg_description

		annotation SummarizationSetBy = Automatic

	/// Drg weight.
	column drg_weight
		dataType: double
		lineageTag: c1080001-0001-0001-0001-000000000042
		sourceLineageTag: drg_weight
		summarizeBy: sum
		sourceColumn: drg_weight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Expected reimbursement.
	column expected_reimbursement
		dataType: double
		lineageTag: c1080001-0001-0001-0001-000000000043
		sourceLineageTag: expected_reimbursement
		summarizeBy: sum
		sourceColumn: expected_reimbursement

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// ETL load audit timestamp. Internal — hide from end users.
	column _load_timestamp
		dataType: dateTime
		formatString: General Date
		lineageTag: c1080001-0001-0001-0001-000000000044
		sourceLineageTag: _load_timestamp
		summarizeBy: none
		sourceColumn: _load_timestamp

		annotation SummarizationSetBy = Automatic

	/// Surrogate join key.
	column encounter_key
		isHidden: true
		dataType: int64
		formatString: 0
		lineageTag: c1080001-0001-0001-0001-000000000045
		sourceLineageTag: encounter_key
		summarizeBy: none
		sourceColumn: encounter_key

		annotation SummarizationSetBy = Automatic

	partition fact_encounter = entity
		mode: directLake
		source
			entityName: fact_encounter
			expressionSource: 'DirectLake - lh_gold_curated'
