/// Claim appeal fact. One row per appeal of a denied claim, with appeal_outcome and amount_recovered.
table fact_appeal
	lineageTag: c1130001-0001-0001-0001-000000000001
	sourceLineageTag: [dbo].[fact_appeal]

	/// Measure: total appeals.
	measure 'Total Appeals' = COUNTROWS(fact_appeal)
		formatString: 0
		lineageTag: c1130001-0001-0001-0001-000000000011
		displayFolder: Denials & Appeals

	/// Measure: appeal recovery $.
	measure 'Appeal Recovery $' = SUM(fact_appeal[appeal_amount_recovered])
		formatString: "\$#,0;(\$#,0);\$0"
		lineageTag: c1130001-0001-0001-0001-000000000012
		displayFolder: Denials & Appeals
		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure: appeal win rate.
	measure 'Appeal Win Rate' =
			VAR _won = CALCULATE(COUNTROWS(fact_appeal), fact_appeal[appeal_outcome] = "Won")
			VAR _total = COUNTROWS(fact_appeal)
			RETURN DIVIDE(_won, _total)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: c1130001-0001-0001-0001-000000000013
		displayFolder: Denials & Appeals

	/// Business key.
	column appeal_id
		dataType: string
		lineageTag: c1130001-0001-0001-0001-000000000021
		sourceLineageTag: appeal_id
		summarizeBy: none
		sourceColumn: appeal_id
		annotation SummarizationSetBy = Automatic

	/// Surrogate join key.
	column appeal_key
		isHidden: true
		dataType: int64
		formatString: 0
		lineageTag: c1130001-0001-0001-0001-000000000022
		sourceLineageTag: appeal_key
		summarizeBy: none
		sourceColumn: appeal_key
		annotation SummarizationSetBy = Automatic

	/// Surrogate join key.
	column claim_key
		isHidden: true
		dataType: int64
		formatString: 0
		lineageTag: c1130001-0001-0001-0001-000000000023
		sourceLineageTag: claim_key
		summarizeBy: none
		sourceColumn: claim_key
		annotation SummarizationSetBy = Automatic

	/// Business key.
	column claim_id
		dataType: string
		lineageTag: c1130001-0001-0001-0001-000000000024
		sourceLineageTag: claim_id
		summarizeBy: none
		sourceColumn: claim_id
		annotation SummarizationSetBy = Automatic

	/// Surrogate join key.
	column member_key
		isHidden: true
		dataType: int64
		formatString: 0
		lineageTag: c1130001-0001-0001-0001-000000000025
		sourceLineageTag: member_key
		summarizeBy: none
		sourceColumn: member_key
		annotation SummarizationSetBy = Automatic

	/// Surrogate key for joining to dim_payer.
	column payer_key
		isHidden: true
		dataType: int64
		formatString: 0
		lineageTag: c1130001-0001-0001-0001-000000000026
		sourceLineageTag: payer_key
		summarizeBy: none
		sourceColumn: payer_key
		annotation SummarizationSetBy = Automatic

	/// Surrogate join key.
	column submit_date_key
		isHidden: true
		dataType: int64
		formatString: 0
		lineageTag: c1130001-0001-0001-0001-000000000027
		sourceLineageTag: submit_date_key
		summarizeBy: none
		sourceColumn: submit_date_key
		annotation SummarizationSetBy = Automatic

	/// Surrogate join key.
	column decision_date_key
		isHidden: true
		dataType: int64
		formatString: 0
		lineageTag: c1130001-0001-0001-0001-000000000028
		sourceLineageTag: decision_date_key
		summarizeBy: none
		sourceColumn: decision_date_key
		annotation SummarizationSetBy = Automatic

	/// Appeal level.
	column appeal_level
		dataType: string
		lineageTag: c1130001-0001-0001-0001-000000000029
		sourceLineageTag: appeal_level
		summarizeBy: none
		sourceColumn: appeal_level
		annotation SummarizationSetBy = Automatic

	/// Appeal level num.
	column appeal_level_num
		dataType: int64
		formatString: 0
		lineageTag: c1130001-0001-0001-0001-00000000002a
		sourceLineageTag: appeal_level_num
		summarizeBy: none
		sourceColumn: appeal_level_num
		annotation SummarizationSetBy = Automatic

	/// Appeal outcome.
	column appeal_outcome
		dataType: string
		lineageTag: c1130001-0001-0001-0001-00000000002b
		sourceLineageTag: appeal_outcome
		summarizeBy: none
		sourceColumn: appeal_outcome
		annotation SummarizationSetBy = Automatic

	/// Appeal amount recovered.
	column appeal_amount_recovered
		dataType: double
		lineageTag: c1130001-0001-0001-0001-00000000002c
		sourceLineageTag: appeal_amount_recovered
		summarizeBy: sum
		sourceColumn: appeal_amount_recovered
		annotation SummarizationSetBy = Automatic
		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Appeal reason.
	column appeal_reason
		dataType: string
		lineageTag: c1130001-0001-0001-0001-00000000002d
		sourceLineageTag: appeal_reason
		summarizeBy: none
		sourceColumn: appeal_reason
		annotation SummarizationSetBy = Automatic

	/// ETL load audit timestamp. Internal — hide from end users.
	column _load_timestamp
		dataType: dateTime
		formatString: General Date
		lineageTag: c1130001-0001-0001-0001-00000000002e
		sourceLineageTag: _load_timestamp
		summarizeBy: none
		sourceColumn: _load_timestamp
		annotation SummarizationSetBy = Automatic

	partition fact_appeal = entity
		mode: directLake
		source
			entityName: fact_appeal
			expressionSource: 'DirectLake - lh_gold_curated'
