/// Claim fact. One row per submitted medical claim. Use denial_flag = 1 for denied claims; denial_risk_category
/// is the preferred filter for risk (do not filter on the raw score).
table fact_claim
	lineageTag: c1090001-0001-0001-0001-000000000001
	sourceLineageTag: [dbo].[fact_claim]

	/// Count of claim records in fact_claim.
	measure 'Total Claims' = COUNTROWS(fact_claim)
		formatString: 0
		lineageTag: c1090001-0001-0001-0001-000000000011

	/// Percentage of claims with denial_flag = 1, computed as denied_claims / total_claims.
	measure 'Denial Rate' =
			VAR _num = CALCULATE(COUNTROWS(fact_claim), fact_claim[denial_flag] = 1)
			VAR _den = COUNTROWS(fact_claim)
			RETURN DIVIDE(_num, _den)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: c1090001-0001-0001-0001-000000000012

	/// Sum of billed_amount across all claims (gross charges submitted to payers).
	measure 'Total Billed' = SUM(fact_claim[billed_amount])
		formatString: "\$#,0;(\$#,0);\$0"
		lineageTag: c1090001-0001-0001-0001-000000000013

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Sum of paid_amount across all claims (actual payer reimbursement received).
	measure 'Total Paid' = SUM(fact_claim[paid_amount])
		formatString: "\$#,0;(\$#,0);\$0"
		lineageTag: c1090001-0001-0001-0001-000000000014

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Total Paid divided by Total Billed. Gross collection rate; lower than Net Collection Rate by the contractual
	/// write-offs.
	measure 'Collection Rate' = DIVIDE([Total Paid], [Total Billed])
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: c1090001-0001-0001-0001-000000000015

	/// Sum of billed_amount for claims with denial_risk_category = 'High'. Forward-looking measure of revenue exposed
	/// to denial.
	measure 'At Risk Revenue' = CALCULATE(SUM(fact_claim[billed_amount]), fact_claim[denial_risk_category] = "High")
		formatString: "\$#,0;(\$#,0);\$0"
		lineageTag: c1090001-0001-0001-0001-000000000016

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Average denial_risk_score across claims. Score is 0-1 from the upstream risk model.
	measure 'Avg Denial Risk' = AVERAGE(fact_claim[denial_risk_score])
		lineageTag: c1090001-0001-0001-0001-000000000017

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Average days from claim submission to payment receipt.
	measure 'Avg Days to Payment' = AVERAGE(fact_claim[days_to_payment])
		lineageTag: c1090001-0001-0001-0001-000000000018

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Average of the row-level net_collection_rate field (paid / allowed). Industry benchmark 95-99%.
	measure 'Net Collection Rate' = AVERAGE(fact_claim[net_collection_rate])
		lineageTag: c1090001-0001-0001-0001-000000000019

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Won appeals divided by total appeals (Won + Lost). Excludes claims never appealed.
	measure 'Appeal Success Rate' =
			VAR _won = CALCULATE(COUNTROWS(fact_claim), fact_claim[appeal_outcome] = "Won")
			VAR _total = CALCULATE(COUNTROWS(fact_claim), fact_claim[appeal_outcome] <> BLANK())
			RETURN DIVIDE(_won, _total)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: c1090001-0001-0001-0001-00000000001a

	/// Sum of appeal_amount_recovered for claims that won an appeal.
	measure 'Total Appeal Recovery' = SUM(fact_claim[appeal_amount_recovered])
		formatString: "\$#,0;(\$#,0);\$0"
		lineageTag: c1090001-0001-0001-0001-00000000001b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure: mtd claims.
	measure 'MTD Claims' = CALCULATE([Total Claims], DATESMTD(dim_date[full_date]))
		formatString: 0
		lineageTag: c1090001-0001-0001-0001-00000000001c

	/// Measure: paid by payment date.
	measure 'Paid by Payment Date' = CALCULATE(SUM(fact_claim[paid_amount]), USERELATIONSHIP(fact_claim[payment_date_key], dim_date[date_key]))
		formatString: "\$#,0;(\$#,0);\$0"
		lineageTag: c1090001-0001-0001-0001-00000000001d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure: high risk denials.
	measure 'High Risk Denials' = CALCULATE(COUNTROWS(fact_claim), fact_claim[denial_risk_category] = "High")
		formatString: 0
		lineageTag: c1090001-0001-0001-0001-00000000001e

	/// Claim business key.
	column claim_id
		dataType: string
		lineageTag: c1090001-0001-0001-0001-000000000021
		sourceLineageTag: claim_id
		summarizeBy: none
		sourceColumn: claim_id

		annotation SummarizationSetBy = Automatic

	/// Date the claim was submitted, as YYYYMMDD integer. Join to dim_date.
	column claim_date_key
		dataType: int64
		formatString: 0
		lineageTag: c1090001-0001-0001-0001-000000000022
		sourceLineageTag: claim_date_key
		summarizeBy: none
		sourceColumn: claim_date_key

		annotation SummarizationSetBy = Automatic

	/// Surrogate join key.
	column payment_date_key
		dataType: int64
		formatString: 0
		lineageTag: c1090001-0001-0001-0001-000000000023
		sourceLineageTag: payment_date_key
		summarizeBy: none
		sourceColumn: payment_date_key

		annotation SummarizationSetBy = Automatic

	/// Surrogate key for joining to dim_patient. Changes across SCD2 versions.
	column patient_key
		dataType: int64
		formatString: 0
		lineageTag: c1090001-0001-0001-0001-000000000024
		sourceLineageTag: patient_key
		summarizeBy: none
		sourceColumn: patient_key

		annotation SummarizationSetBy = Automatic

	/// Surrogate key for joining to dim_provider.
	column provider_key
		dataType: int64
		formatString: 0
		lineageTag: c1090001-0001-0001-0001-000000000025
		sourceLineageTag: provider_key
		summarizeBy: none
		sourceColumn: provider_key

		annotation SummarizationSetBy = Automatic

	/// Surrogate key for joining to dim_payer.
	column payer_key
		dataType: int64
		formatString: 0
		lineageTag: c1090001-0001-0001-0001-000000000026
		sourceLineageTag: payer_key
		summarizeBy: none
		sourceColumn: payer_key

		annotation SummarizationSetBy = Automatic

	/// Surrogate join key.
	column encounter_key
		dataType: int64
		formatString: 0
		lineageTag: c1090001-0001-0001-0001-000000000027
		sourceLineageTag: encounter_key
		summarizeBy: none
		sourceColumn: encounter_key

		annotation SummarizationSetBy = Automatic

	/// Surrogate join key.
	column facility_key
		dataType: int64
		formatString: 0
		lineageTag: c1090001-0001-0001-0001-000000000028
		sourceLineageTag: facility_key
		summarizeBy: none
		sourceColumn: facility_key

		annotation SummarizationSetBy = Automatic

	/// Claim type.
	column claim_type
		dataType: string
		lineageTag: c1090001-0001-0001-0001-000000000029
		sourceLineageTag: claim_type
		summarizeBy: none
		sourceColumn: claim_type

		annotation SummarizationSetBy = Automatic

	/// Claim status: Submitted, Pending, Paid, Denied, Appealed.
	column claim_status
		dataType: string
		lineageTag: c1090001-0001-0001-0001-00000000002a
		sourceLineageTag: claim_status
		summarizeBy: none
		sourceColumn: claim_status

		annotation SummarizationSetBy = Automatic

	/// Gross amount billed to payer (charges submitted).
	column billed_amount
		dataType: double
		lineageTag: c1090001-0001-0001-0001-00000000002b
		sourceLineageTag: billed_amount
		summarizeBy: sum
		sourceColumn: billed_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Amount the payer agrees is allowable per contract.
	column allowed_amount
		dataType: double
		lineageTag: c1090001-0001-0001-0001-00000000002c
		sourceLineageTag: allowed_amount
		summarizeBy: sum
		sourceColumn: allowed_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Amount actually paid by the payer.
	column paid_amount
		dataType: double
		lineageTag: c1090001-0001-0001-0001-00000000002d
		sourceLineageTag: paid_amount
		summarizeBy: sum
		sourceColumn: paid_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// 1 = claim denied; 0 = paid or pending.
	column denial_flag
		dataType: int64
		formatString: 0
		lineageTag: c1090001-0001-0001-0001-00000000002e
		sourceLineageTag: denial_flag
		summarizeBy: none
		sourceColumn: denial_flag

		annotation SummarizationSetBy = Automatic

	/// Model-predicted probability of denial (0-1). Do NOT filter directly; use denial_risk_category.
	column denial_risk_score
		dataType: double
		lineageTag: c1090001-0001-0001-0001-00000000002f
		sourceLineageTag: denial_risk_score
		summarizeBy: none
		sourceColumn: denial_risk_score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Denial risk band: High, Medium, Low. Preferred filter for risk.
	column denial_risk_category
		dataType: string
		lineageTag: c1090001-0001-0001-0001-000000000030
		sourceLineageTag: denial_risk_category
		summarizeBy: none
		sourceColumn: denial_risk_category

		annotation SummarizationSetBy = Automatic

	/// Free-text reason the claim was denied (e.g. Missing Authorization, Coding Error).
	column primary_denial_reason
		dataType: string
		lineageTag: c1090001-0001-0001-0001-000000000031
		sourceLineageTag: primary_denial_reason
		summarizeBy: none
		sourceColumn: primary_denial_reason

		annotation SummarizationSetBy = Automatic

	/// System-suggested remediation action for the denial.
	column recommended_action
		dataType: string
		lineageTag: c1090001-0001-0001-0001-000000000032
		sourceLineageTag: recommended_action
		summarizeBy: none
		sourceColumn: recommended_action

		annotation SummarizationSetBy = Automatic

	/// Days from claim submission to payment.
	column days_to_payment
		dataType: int64
		formatString: 0
		lineageTag: c1090001-0001-0001-0001-000000000033
		sourceLineageTag: days_to_payment
		summarizeBy: sum
		sourceColumn: days_to_payment

		annotation SummarizationSetBy = Automatic

	/// Row-level net collection rate (paid / allowed).
	column net_collection_rate
		dataType: double
		lineageTag: c1090001-0001-0001-0001-000000000034
		sourceLineageTag: net_collection_rate
		summarizeBy: average
		sourceColumn: net_collection_rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Date column.
	column appeal_date
		dataType: dateTime
		formatString: General Date
		lineageTag: c1090001-0001-0001-0001-000000000035
		sourceLineageTag: appeal_date
		summarizeBy: none
		sourceColumn: appeal_date

		annotation SummarizationSetBy = Automatic

	/// Appeal result: Won, Lost, In Progress, or blank if not appealed.
	column appeal_outcome
		dataType: string
		lineageTag: c1090001-0001-0001-0001-000000000036
		sourceLineageTag: appeal_outcome
		summarizeBy: none
		sourceColumn: appeal_outcome

		annotation SummarizationSetBy = Automatic

	/// Dollars recovered via a successful appeal.
	column appeal_amount_recovered
		dataType: double
		lineageTag: c1090001-0001-0001-0001-000000000037
		sourceLineageTag: appeal_amount_recovered
		summarizeBy: sum
		sourceColumn: appeal_amount_recovered

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// ETL load audit timestamp. Internal — hide from end users.
	column _load_timestamp
		dataType: dateTime
		formatString: General Date
		lineageTag: c1090001-0001-0001-0001-000000000038
		sourceLineageTag: _load_timestamp
		summarizeBy: none
		sourceColumn: _load_timestamp

		annotation SummarizationSetBy = Automatic

	/// Surrogate join key.
	column claim_key
		dataType: int64
		formatString: 0
		lineageTag: c1090001-0001-0001-0001-000000000039
		sourceLineageTag: claim_key
		summarizeBy: none
		sourceColumn: claim_key

		annotation SummarizationSetBy = Automatic

	partition fact_claim = entity
		mode: directLake
		source
			entityName: fact_claim
			expressionSource: 'DirectLake - lh_gold_curated'
