/// Provider capitation payments. Monthly per-member-per-month (PMPM) payments from payer to provider under
/// value-based contracts.
table fact_capitation
	lineageTag: c1120001-0001-0001-0001-000000000001
	sourceLineageTag: [dbo].[fact_capitation]

	/// Measure: total capitation paid.
	measure 'Total Capitation Paid' = SUM(fact_capitation[capitation_pmpm])
		lineageTag: c1120001-0001-0001-0001-000000000011
		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure: avg capitation pmpm.
	measure 'Avg Capitation PMPM' = AVERAGE(fact_capitation[capitation_pmpm])
		lineageTag: c1120001-0001-0001-0001-000000000012
		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Measure: avg withhold %.
	measure 'Avg Withhold %' = AVERAGE(fact_capitation[withhold_pct])
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: c1120001-0001-0001-0001-000000000013

	/// Business key.
	column capitation_id
		dataType: string
		lineageTag: c1120001-0001-0001-0001-000000000021
		sourceLineageTag: capitation_id
		summarizeBy: none
		sourceColumn: capitation_id
		annotation SummarizationSetBy = Automatic

	/// Surrogate join key.
	column capitation_key
		dataType: int64
		formatString: 0
		lineageTag: c1120001-0001-0001-0001-000000000022
		sourceLineageTag: capitation_key
		summarizeBy: none
		sourceColumn: capitation_key
		annotation SummarizationSetBy = Automatic

	/// Year month.
	column year_month
		dataType: string
		lineageTag: c1120001-0001-0001-0001-000000000023
		sourceLineageTag: year_month
		summarizeBy: none
		sourceColumn: year_month
		annotation SummarizationSetBy = Automatic

	/// Surrogate join key.
	column member_key
		dataType: int64
		formatString: 0
		lineageTag: c1120001-0001-0001-0001-000000000024
		sourceLineageTag: member_key
		summarizeBy: none
		sourceColumn: member_key
		annotation SummarizationSetBy = Automatic

	/// Surrogate key for joining to dim_provider.
	column provider_key
		dataType: int64
		formatString: 0
		lineageTag: c1120001-0001-0001-0001-000000000025
		sourceLineageTag: provider_key
		summarizeBy: none
		sourceColumn: provider_key
		annotation SummarizationSetBy = Automatic

	/// Surrogate key for joining to dim_payer.
	column payer_key
		dataType: int64
		formatString: 0
		lineageTag: c1120001-0001-0001-0001-000000000026
		sourceLineageTag: payer_key
		summarizeBy: none
		sourceColumn: payer_key
		annotation SummarizationSetBy = Automatic

	/// Surrogate key for joining to dim_plan.
	column plan_key
		dataType: int64
		formatString: 0
		lineageTag: c1120001-0001-0001-0001-000000000027
		sourceLineageTag: plan_key
		summarizeBy: none
		sourceColumn: plan_key
		annotation SummarizationSetBy = Automatic

	/// Capitation pmpm.
	column capitation_pmpm
		dataType: double
		lineageTag: c1120001-0001-0001-0001-000000000028
		sourceLineageTag: capitation_pmpm
		summarizeBy: sum
		sourceColumn: capitation_pmpm
		annotation SummarizationSetBy = Automatic
		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Percentage (0-1 unless otherwise noted).
	column withhold_pct
		dataType: double
		lineageTag: c1120001-0001-0001-0001-000000000029
		sourceLineageTag: withhold_pct
		summarizeBy: average
		sourceColumn: withhold_pct
		annotation SummarizationSetBy = Automatic

	/// Bonus eligible.
	column bonus_eligible
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: c1120001-0001-0001-0001-00000000002a
		sourceLineageTag: bonus_eligible
		summarizeBy: none
		sourceColumn: bonus_eligible
		annotation SummarizationSetBy = Automatic

	/// ETL load audit timestamp. Internal — hide from end users.
	column _load_timestamp
		dataType: dateTime
		formatString: General Date
		lineageTag: c1120001-0001-0001-0001-00000000002b
		sourceLineageTag: _load_timestamp
		summarizeBy: none
		sourceColumn: _load_timestamp
		annotation SummarizationSetBy = Automatic

	partition fact_capitation = entity
		mode: directLake
		source
			entityName: fact_capitation
			expressionSource: 'DirectLake - lh_gold_curated'
