# Fabric notebook source

# METADATA **{"language":"markdown"}**

# MARKDOWN **{"language":"markdown"}**

# # RTI Use Case 2: Care Gap Closure at Point of Care
# 
# When a patient arrives at a facility (ADT event), this notebook:
# 1. Joins the ADT event with the patient's **open HEDIS care gaps**
# 2. Checks if the visit type/diagnosis could close an existing gap
# 3. Generates **priority-ranked alerts** for the care team
# 
# **Industry pain point:** Payers spend millions on member outreach for HEDIS gaps,
# but the highest-value moment is when the patient is *already in front of a provider*.
# Real-time alerting at the point of care drives gap closure rates from ~30% to 60%+.
# 
# **Input:** `rti_adt_events` (Delta) + `care_gaps` + `hedis_measures`
# **Output:** `rti_care_gap_alerts` (Delta)
# 
# **Default lakehouse:** `lh_gold_curated`

# METADATA **{"language":"python"}**

# CELL **{"language":"python"}**

# ============================================================================
# NB_RTI_Care_Gap_Alerts
# ============================================================================
# Point-of-care gap closure: When a patient has an encounter,
# check for open HEDIS care gaps and alert the care team.
#
# Default lakehouse: lh_gold_curated
# ============================================================================

print("NB_RTI_Care_Gap_Alerts: Starting...")

# METADATA **{"language":"python"}**

# CELL **{"language":"python"}**

# Install Kusto SDK if missing (compatible with child-notebook execution)
import importlib, subprocess, sys
for _pkg in ["azure.kusto.data", "azure.kusto.ingest", "azure.core"]:
    try:
        importlib.import_module(_pkg)
    except ImportError:
        subprocess.check_call(
            [sys.executable, "-m", "pip", "install",
             "azure-kusto-data", "azure-kusto-ingest", "azure-core>=1.31.0", "-q"])
        break

# METADATA **{"language":"python"}**

# CELL **{"language":"python"}**

from pyspark.sql import functions as F
from pyspark.sql.types import StringType

# METADATA **{"language":"python"}**

# CELL **{"language":"python"}**

# ---------- Load data ----------
print("Loading ADT events and care gap data...")

df_adt = spark.table("lh_gold_curated.rti_adt_events")
df_patients = spark.sql("""
    SELECT patient_id, first_name, last_name, gender, date_of_birth, zip_code
    FROM lh_gold_curated.dim_patient WHERE is_current = true
""")
df_facilities = spark.sql("SELECT facility_id, facility_name, latitude, longitude FROM lh_gold_curated.dim_facility")

# Load care gaps (generated by NB_Generate_Sample_Data)
try:
    df_care_gaps = spark.table("lh_gold_curated.care_gaps")
    print(f"  Care gaps table: {df_care_gaps.count()} rows")
except Exception:
    # Try reading from bronze CSV
    try:
        df_care_gaps = spark.read.option("header", True).csv("Files/care_gaps.csv")
        print(f"  Care gaps from CSV: {df_care_gaps.count()} rows")
    except Exception:
        # Graceful degradation -- create empty DataFrame so notebook completes
        from pyspark.sql.types import StructType, StructField, StringType, IntegerType
        schema = StructType([
            StructField("patient_id", StringType(), True),
            StructField("measure_id", StringType(), True),
            StructField("measure_name", StringType(), True),
            StructField("is_gap_open", StringType(), True),
            StructField("gap_days_overdue", IntegerType(), True),
        ])
        df_care_gaps = spark.createDataFrame([], schema)
        print("  WARNING: No care_gaps table or CSV found. Using empty DataFrame.")
        print("  Run NB_Generate_Sample_Data to populate care gaps for full alert generation.")

# Load HEDIS measure definitions
try:
    df_hedis = spark.table("lh_gold_curated.hedis_measures")
except Exception:
    try:
        df_hedis = spark.read.option("header", True).csv("Files/hedis_measures.csv")
    except Exception:
        df_hedis = None
        print("  HEDIS measures not found -- will use measure_id only")

print(f"  ADT events: {df_adt.count()}")
print(f"  Patients: {df_patients.count()}")

# METADATA **{"language":"python"}**

# CELL **{"language":"python"}**

# ============================================================================
# Care Gap Alert Logic
# ============================================================================

# Filter to ADMIT and OBSERVATION events (patient is present for care)
# Drop columns that also exist in dim_facility to avoid ambiguous references after join
df_encounters = df_adt.drop("facility_name", "latitude", "longitude").filter(
    F.col("event_type").isin("ADMIT", "OBSERVATION")
)

# Filter to open gaps only
df_open_gaps = df_care_gaps.filter(F.col("is_gap_open") == "true")

print(f"  Actionable encounters (ADMIT/OBSERVATION): {df_encounters.count()}")
print(f"  Open care gaps: {df_open_gaps.count()}")

# METADATA **{"language":"python"}**

# CELL **{"language":"python"}**

# ---------- Join encounters with open care gaps ----------
df_alerts = (
    df_encounters
    .join(df_open_gaps, "patient_id", "inner")
    .join(df_patients, "patient_id", "left")
    .join(df_facilities, "facility_id", "left")
)

# Enrich with HEDIS measure details (authoritative measure_name source)
if df_hedis is not None:
    # Rename care_gaps measure_name before join to avoid ambiguity
    df_alerts = df_alerts.withColumnRenamed("measure_name", "_cg_measure_name")
    df_alerts = df_alerts.join(
        df_hedis.select(
            F.col("measure_id").alias("h_measure_id"),
            F.col("measure_name").alias("_hedis_measure_name"),
            "description",
            "frequency_months"
        ),
        df_alerts["measure_id"] == F.col("h_measure_id"),
        "left"
    ).drop("h_measure_id")
    # Unify: prefer HEDIS measure_name, fall back to care_gaps, then measure_id
    df_alerts = df_alerts.withColumn(
        "measure_name",
        F.coalesce(F.col("_hedis_measure_name"), F.col("_cg_measure_name"), F.col("measure_id"))
    ).drop("_cg_measure_name", "_hedis_measure_name")
else:
    # No HEDIS table -- ensure measure_name always has a value
    df_alerts = df_alerts.withColumn(
        "measure_name", F.coalesce(F.col("measure_name"), F.col("measure_id"))
    )

print(f"  Patient-encounter-gap matches: {df_alerts.count()}")

# METADATA **{"language":"python"}**

# CELL **{"language":"python"}**

# ============================================================================
# Priority Ranking and Alert Generation
# ============================================================================

# Priority based on gap overdue days and measure criticality
CRITICAL_MEASURES = ["CDC", "BCS", "COL"]  # Diabetes, breast cancer, colorectal

df_alerts = df_alerts.withColumn(
    "gap_days_overdue_int",
    F.coalesce(F.col("gap_days_overdue").cast("int"), F.lit(0))
)

df_alerts = df_alerts.withColumn(
    "alert_priority",
    F.when(
        (F.col("measure_id").isin(CRITICAL_MEASURES)) & (F.col("gap_days_overdue_int") > 180),
        "CRITICAL"
    )
    .when(F.col("gap_days_overdue_int") > 365, "CRITICAL")
    .when(
        (F.col("measure_id").isin(CRITICAL_MEASURES)) | (F.col("gap_days_overdue_int") > 90),
        "HIGH"
    )
    .when(F.col("gap_days_overdue_int") > 30, "MEDIUM")
    .otherwise("LOW")
)

# Generate human-readable alert text
df_alerts = df_alerts.withColumn(
    "alert_text",
    F.concat(
        F.lit("CARE GAP ALERT: Patient "),
        F.coalesce(F.col("first_name"), F.lit("")),
        F.lit(" "),
        F.coalesce(F.col("last_name"), F.lit("")),
        F.lit(" has an open "),
        F.col("measure_id"),
        F.lit(" gap ("),
        F.coalesce(F.col("measure_name"), F.col("measure_id")),
        F.lit("), overdue by "),
        F.col("gap_days_overdue_int").cast("string"),
        F.lit(" days. Consider ordering during this visit.")
    )
)

# Select final output
df_output = df_alerts.select(
    F.expr("uuid()").alias("alert_id"),
    F.current_timestamp().alias("alert_timestamp"),
    "event_id",
    "event_timestamp",
    "patient_id",
    F.col("first_name").alias("patient_first_name"),
    F.col("last_name").alias("patient_last_name"),
    "facility_id",
    F.coalesce(F.col("facility_name"), F.lit("Unknown")).alias("facility_name"),
    "event_type",
    "admission_type",
    "primary_diagnosis",
    "measure_id",
    F.coalesce(F.col("measure_name"), F.col("measure_id")).alias("measure_name"),
    "gap_days_overdue_int",
    "alert_priority",
    "alert_text",
    F.coalesce(F.col("latitude"), F.lit(42.96)).alias("latitude"),
    F.coalesce(F.col("longitude"), F.lit(-85.67)).alias("longitude"),
)

df_output.write.format("delta").mode("overwrite").saveAsTable("lh_gold_curated.rti_care_gap_alerts")
alert_count = df_output.count()
print(f"Care gap alerts written: {alert_count}")


# METADATA **{"language":"python"}**

# CELL **{"language":"python"}**

# ============================================================================
# Push Care Gap Alerts to KQL (direct Kusto ingestion)
# ============================================================================
print("Pushing care gap alerts to KQL...")

import requests as _requests
import json as _json

_BASE_URL = "https://api.fabric.microsoft.com/v1"
_WORKSPACE_ID = notebookutils.runtime.context.get("currentWorkspaceId", "")
_KQL_DB_NAME = "Healthcare_RTI_DB"

def _get_fabric_token():
    return notebookutils.credentials.getToken("https://analysis.windows.net/powerbi/api")

def _get_kusto_token():
    return notebookutils.credentials.getToken("kusto")

_KUSTO_QUERY_URI = ""
_KUSTO_INGEST_URI = ""
_headers = {"Authorization": f"Bearer {_get_fabric_token()}", "Content-Type": "application/json"}
_resp = _requests.get(f"{_BASE_URL}/workspaces/{_WORKSPACE_ID}/items?type=Eventhouse", headers=_headers)
if _resp.status_code == 200:
    for _item in _resp.json().get("value", []):
        if "Healthcare" in _item.get("displayName", ""):
            _props_resp = _requests.get(
                f"{_BASE_URL}/workspaces/{_WORKSPACE_ID}/eventhouses/{_item['id']}",
                headers=_headers
            )
            if _props_resp.status_code == 200:
                _props = _props_resp.json().get("properties", _props_resp.json())
                _KUSTO_QUERY_URI = _props.get("queryServiceUri", "")
                _KUSTO_INGEST_URI = _props.get("ingestionServiceUri", "")
                if not _KUSTO_INGEST_URI and _KUSTO_QUERY_URI:
                    _KUSTO_INGEST_URI = _KUSTO_QUERY_URI.replace("https://", "https://ingest-")
            break

if _KUSTO_QUERY_URI and _KUSTO_INGEST_URI:
    try:
        from azure.kusto.ingest import ManagedStreamingIngestClient, IngestionProperties
        from azure.kusto.data import KustoConnectionStringBuilder, DataFormat
        import io

        _df_kql = df_output.select(
            "alert_id", "alert_timestamp", "patient_id", "facility_id",
            "facility_name", "measure_id", "measure_name",
            F.col("gap_days_overdue_int").alias("gap_days_overdue"),
            "alert_priority", "alert_text", "latitude", "longitude"
        ).toPandas()

        _token = _get_kusto_token()
        _engine_kcsb = KustoConnectionStringBuilder.with_aad_user_token_authentication(_KUSTO_QUERY_URI, _token)
        _dm_kcsb = KustoConnectionStringBuilder.with_aad_user_token_authentication(_KUSTO_INGEST_URI, _token)
        _client = ManagedStreamingIngestClient(_engine_kcsb, _dm_kcsb)
        _ingestion_props = IngestionProperties(
            database=_KQL_DB_NAME, table="care_gap_alerts",
            data_format=DataFormat.JSON, ingestion_mapping_reference="care_gap_alerts_mapping"
        )
        _json_data = _df_kql.to_json(orient="records", lines=True, date_format="iso")
        _client.ingest_from_stream(io.StringIO(_json_data), ingestion_properties=_ingestion_props)
        print(f"  KQL: {len(_df_kql)} care gap alerts streamed -> care_gap_alerts")
    except Exception as e:
        print(f"  KQL WARN: care_gap_alerts ingestion failed: {e}")
else:
    print("  KQL: Eventhouse not found -- skipping KQL ingestion (Delta table still written)")

# METADATA **{"language":"python"}**

# CELL **{"language":"python"}**

# ============================================================================
# Summary Statistics
# ============================================================================

df_summary = spark.sql("""
    SELECT
        alert_priority,
        COUNT(*) as alert_count,
        COUNT(DISTINCT patient_id) as unique_patients,
        COUNT(DISTINCT facility_id) as facilities_involved,
        COUNT(DISTINCT measure_id) as measures_flagged
    FROM lh_gold_curated.rti_care_gap_alerts
    GROUP BY alert_priority
    ORDER BY
        CASE alert_priority
            WHEN 'CRITICAL' THEN 1
            WHEN 'HIGH' THEN 2
            WHEN 'MEDIUM' THEN 3
            ELSE 4
        END
""")

print("\n" + "=" * 60)
print("CARE GAP CLOSURE RESULTS")
print("=" * 60)
df_summary.show(truncate=False)

# Gap distribution by measure
df_by_measure = spark.sql("""
    SELECT
        measure_id,
        measure_name,
        COUNT(*) as alerts,
        COUNT(DISTINCT patient_id) as patients,
        ROUND(AVG(gap_days_overdue_int), 0) as avg_days_overdue
    FROM lh_gold_curated.rti_care_gap_alerts
    GROUP BY measure_id, measure_name
    ORDER BY alerts DESC
""")

print("Alerts by HEDIS Measure:")
df_by_measure.show(truncate=False)

# Facility hotspots
df_by_facility = spark.sql("""
    SELECT
        facility_name,
        COUNT(*) as total_alerts,
        SUM(CASE WHEN alert_priority = 'CRITICAL' THEN 1 ELSE 0 END) as critical_alerts,
        COUNT(DISTINCT patient_id) as unique_patients
    FROM lh_gold_curated.rti_care_gap_alerts
    GROUP BY facility_name
    ORDER BY total_alerts DESC
""")

print("Alerts by Facility (map visual data):")
df_by_facility.show(truncate=False)

print("\nNB_RTI_Care_Gap_Alerts: COMPLETE")
print("=" * 60)

# METADATA **{"language":"python"}**
